### ISSUE TITLE
ImportError: DLL load failed while importing hwm14: The specified module could not be found.

### ISSUE THREAD

**Issue by benboyde** [rilma/pyHWM14#9]
Hi, I'm having some trouble getting the module working. I've tried both the pip install and install from source code methods in python 3.10 and python 3.8. Every time the install process runs fine, but when I try the test it gives the following error.

======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "C:\Users\mouse\anaconda3\envs\test\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\mouse\anaconda3\envs\test\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Users\mouse\pyHWM14\tests\test.py", line 2, in <module>
    from pyhwm2014 import HWM14
  File "C:\Users\mouse\pyHWM14\pyhwm2014\__init__.py", line 7, in <module>
    from . import hwm14
ImportError: DLL load failed while importing hwm14: The specified module could not be found.

In the folder "C:\Users\mouse\pyHWM14\pyhwm2014" there is a file called "hwm14.cp38-win_amd64.pyd" (and a corresponding cp310 file from the python 3.10 install). I think this is the file it should be looking for at this point? But I'm not sure why it's having this issue.

**Comment by rilma** [comment]
Based on current main branch, the provided code is not being built and tested in Windows. Any contribution in compiling the wrapper in Windows and submission of related solution via pull request is more than welcome.
